### ISSUE TITLE
Problem with AR collection

### ISSUE THREAD

**Issue by memumen** [DmitryTsepelev/graphql-ruby-fragment_cache#21]
I have problem with AR collections.
When I try to read a collection, I get an error related to the cache key

rails 6.0.3.1
graphql-fragment_cache 0.1.5
graphql 1.10.10
ruby 2.7.1

```
module Types
  class QueryType < Types::BaseObject
    field :exercise, Types::ExerciseType, resolver: Queries::ExerciseQuery
    field :exercises, [Types::ExerciseType], resolver: Queries::ExercisesQuery, cache_fragment: true
 end
end
```

```
module Types
  class ExerciseType < Types::BaseObject
    field :id, ID, null: false
    field :course_id, ID, null: false, cache_fragment: true
  end
end
```

And resolvers

```
module Queries
  class ExerciseResolver < Queries::BaseQuery
    argument :id, ID, required: true
    type Types::ExerciseType, null: true

    def resolve(id:)
      Exercise.find(id)
    end
  end
end
```

```
module Queries
  class ExercisesResolver < Queries::BaseQuery
    type [Types::ExerciseType], null: true

    def resolve(id:)
      Exercise.all
    end
  end
end
```

and when I trying to get a collection if any of fields Types::ExerciseType uses caching, then I get an error

```
rails_1        | [9ecf2522-ed52-4d25-b5b1-62631be97a01] Failed to look ahead the field: 0
rails_1        | [9ecf2522-ed52-4d25-b5b1-62631be97a01] /usr/local/bundle/gems/graphql-fragment_cache-0.1.5/lib/graphql/fragment_cache/cache_key_builder.rb:137:in `block in path_cache_key'
rails_1        | /usr/local/bundle/gems/graphql-fragment_cache-0.1.5/lib/graphql/fragment_cache/cache_key_builder.rb:135:in `map'
rails_1        | /usr/local/bundle/gems/graphql-fragment_cache-0.1.5/lib/graphql/fragment_cache/cache_key_builder.rb:135:in `path_cache_key'
rails_1        | /usr/local/bundle/gems/graphql-fragment_cache-0.1.5/lib/graphql/fragment_cache/cache_key_builder.rb:122:in `query_cache_key'
rails_1        | /usr/local/bundle/gems/graphql-fragment_cache-0.1.5/lib/graphql/fragment_cache/cache_key_builder.rb:109:in `build'
rails_1        | /usr/local/bundle/gems/graphql-fragment_cache-0.1.5/lib/graphql/fragment_cache/cache_key_builder.rb:94:in `call'
rails_1        | /usr/local/bundle/gems/graphql-fragment_cache-0.1.5/lib/graphql/fragment_cache/fragment.rb:31:in `cache_key'
rails_1        | /usr/local/bundle/gems/graphql-fragment_cache-0.1.5/lib/graphql/fragment_cache/fragment.rb:20:in `read'
rails_1        | /usr/local/bundle/gems/graphql-fragment_cache-0.1.5/lib/graphql/fragment_cache/object_helpers.rb:26:in `cache_fragment'
rails_1        | /usr/local/bundle/gems/graphql-fragment_cache-0.1.5/lib/graphql/fragment_cache/field_extension.rb:52:in `resolve'
rails_1        | /usr/local/bundle/gems/graphql-1.10.10/lib/graphql/schema/field.rb:757:in `run_extensions_before_resolve'
rails_1        | /usr/local/bundle/gems/graphql-1.10.10/lib/graphql/schema/field.rb:739:in `with_extensions'
rails_1        | /usr/local/bundle/gems/graphql-1.10.10/lib/graphql/schema/field.rb:561:in `resolve'
```

**Comment by DmitryTsepelev** [comment]
Hi @memumen! Thanks for catching it, I'll investigate this case.

**Comment by DmitryTsepelev** [comment]
@memumen I found the problem (#22) and version 0.1.6 is on it's way, please let me know if it does not help

**Comment by memumen** [comment]
@DmitryTsepelev, @palkan  I just tried, it works good. Thanks for quick solution.
